name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2
      - uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: bun install
      - run: bun run build
      - run: docker build -t ${{ secrets.DOCKER_REGISTRY }}/dsm-water-polo-website .
      - run: docker push ${{ secrets.DOCKER_REGISTRY }}/dsm-water-polo-website
      # - run: curl -X POST ${{ secrets.DEPLOY_WEBHOOK_URL }}
